export const viewerHTML = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>CU · Live desktop</title><style>
*{box-sizing:border-box}body{margin:0;background:#111214;color:#eee;font:14px system-ui,-apple-system,sans-serif}header{height:70px;display:flex;align-items:center;gap:16px;padding:0 24px;border-bottom:1px solid #323337}strong{font-size:26px;letter-spacing:-2px}#badge{font:11px monospace;text-transform:uppercase;letter-spacing:1px;color:#a9b5ff}#title{flex:1;color:#b9bac0;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}button{background:#24262a;color:#fff;border:1px solid #45474d;border-radius:7px;padding:10px 16px;cursor:pointer}button.primary{background:#e9ecff;color:#151722;border-color:#e9ecff}button:disabled{opacity:.4;cursor:default}main{padding:24px;display:grid;place-items:center;height:calc(100vh - 140px)}#stage{position:relative;max-width:100%;max-height:100%;display:flex;outline:none}#screen{object-fit:contain;max-width:100%;max-height:calc(100vh - 190px);border:1px solid #393b40;border-radius:8px;user-select:none}#cursor{position:absolute;pointer-events:none;display:none;width:15px;height:15px;background:#c4cdff;clip-path:polygon(0 0,100% 65%,55% 65%,35% 100%);filter:drop-shadow(0 1px 2px #000)}footer{height:70px;padding:12px 24px;border-top:1px solid #323337;display:flex;align-items:center;gap:18px}#message{flex:1;color:#b9bac0}#fps{font:11px monospace;color:#81858c}input{background:#202226;border:1px solid #45474d;color:white;padding:10px;border-radius:7px;width:220px}#empty{position:absolute;inset:0;display:grid;place-items:center;color:#aaa}
</style><header><strong>CU</strong><span id="badge">CONNECTING</span><span id="title">Live desktop</span><button id="take" class="primary">Take control / Stop agent</button><button id="resume" disabled>Return to agent</button></header>
<main><div id="stage" tabindex="0"><img id="screen" alt="Live controlled window" draggable="false"><div id="cursor"></div></div></main>
<section id="dialog" hidden style="padding:12px 24px;background:#262a35"><span id="dialogMessage"></span> <input id="dialogText" aria-label="Dialog answer"><button id="accept">Accept</button><button id="dismiss">Dismiss</button></section><footer><span id="message" role="status">Connecting to the session…</span><input id="text" placeholder="Type exact text" aria-label="Text to type"><button id="send">Send text</button><span id="fps"></span></footer>
<script>
const token=location.hash.slice(1)||sessionStorage.getItem('cu-viewer-token')||'';sessionStorage.setItem('cu-viewer-token',token);history.replaceState(null,'',location.pathname);const headers={Authorization:'Bearer '+token};let owner='agent',pending=false,lastURL,down,clickTimer,dialogId,frameId;
const $=id=>document.getElementById(id);
async function call(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{...headers,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){let d=await r.json().catch(()=>({error:r.statusText}));throw Error(d.error||r.statusText)}return r}
async function control(path,body={}){if(path==='input')body={...body,frameId};try{await call(path,body);await state()}catch(e){$('message').textContent=e.message}}
async function state(){const r=await call('state'),s=await r.json();owner=s.owner;const dialog=s.dialogs?.[0];dialogId=dialog?.id;$('dialog').hidden=!dialog;$('dialogMessage').textContent=dialog?.message||'';$('accept').disabled=owner!=='human';$('dismiss').disabled=owner!=='human';$('badge').textContent=owner==='human'?'YOU HAVE CONTROL':s.state;$('title').textContent=s.title||'Live desktop';$('message').textContent=s.message||'';$('take').disabled=!s.canControl||owner==='human';$('resume').disabled=!s.canControl||owner!=='human';$('send').disabled=owner!=='human';$('text').disabled=owner!=='human';if(owner==='agent'){const p=s.pointer,img=$('screen');if(p&&Date.now()-(s.pointerAt||0)<1200&&img.naturalWidth){$('cursor').style.cssText='display:block;left:'+(p.x*img.clientWidth/img.naturalWidth)+'px;top:'+(p.y*img.clientHeight/img.naturalHeight)+'px'}else $('cursor').style.display='none'}}
$('accept').onclick=()=>control('input',{kind:'dialog',dialogId,accept:true,text:$('dialogText').value});$('dismiss').onclick=()=>control('input',{kind:'dialog',dialogId,accept:false});
$('take').onclick=()=>control('takeover');$('resume').onclick=()=>control('resume');$('send').onclick=()=>{if($('text').value)control('input',{kind:'type',text:$('text').value})};
function point(e){const r=$('screen').getBoundingClientRect();return {x:Math.max(0,Math.min($('screen').naturalWidth-1,(e.clientX-r.left)*$('screen').naturalWidth/r.width)),y:Math.max(0,Math.min($('screen').naturalHeight-1,(e.clientY-r.top)*$('screen').naturalHeight/r.height))}}
async function input(a){if(owner!=='human'||pending)return;pending=true;try{await control('input',a)}finally{pending=false}}
$('stage').onpointerdown=e=>{if(owner!=='human')return;down=point(e);$('stage').setPointerCapture(e.pointerId);$('stage').focus()};
$('stage').onpointerup=e=>{if(!down||owner!=='human')return;const p=point(e),start=down;down=null;if(Math.hypot(p.x-start.x,p.y-start.y)>8){clearTimeout(clickTimer);input({kind:'drag',...start,toX:p.x,toY:p.y})}else if(e.button===2){input({kind:'rightClick',...p})}else{clearTimeout(clickTimer);clickTimer=setTimeout(()=>input({kind:'click',...p}),230)}};
$('stage').ondblclick=e=>{clearTimeout(clickTimer);input({kind:'doubleClick',...point(e)})};
$('stage').oncontextmenu=e=>e.preventDefault();$('stage').onwheel=e=>{if(owner==='human'){e.preventDefault();input({kind:'scroll',amount:e.deltaY>0?3:-3})}};
$('stage').onkeydown=e=>{if(owner!=='human')return;const named={Enter:'Enter',Escape:'Escape',Tab:e.shiftKey?'Shift+Tab':'Tab',Backspace:'Backspace',ArrowUp:'ArrowUp',ArrowDown:'ArrowDown',ArrowLeft:'ArrowLeft',ArrowRight:'ArrowRight',' ':'Space'};const text=(e.ctrlKey||e.metaKey)?'Control+'+e.key.toUpperCase():named[e.key];if(text){e.preventDefault();input({kind:'key',text})}};
$('stage').onpointermove=e=>{if(owner!=='human')return;const r=$('stage').getBoundingClientRect();$('cursor').style.cssText='display:block;left:'+(e.clientX-r.left)+'px;top:'+(e.clientY-r.top)+'px'};
async function loop(){let start=performance.now();try{await state();const r=await call('frame');frameId=r.headers.get('X-CU-Frame');const blob=await r.blob();const next=URL.createObjectURL(blob);$('screen').src=next;if(lastURL)URL.revokeObjectURL(lastURL);lastURL=next;$('fps').textContent=Math.round(performance.now()-start)+' ms/frame'}catch(e){$('message').textContent=e.message}setTimeout(loop,200)}loop();
</script></html>`;
