import type { Candidate, Snapshot } from '../shared/contracts.js';

/** Bind options to refs and preserve descendant labels on otherwise unnamed cards. */
export function pressCandidates(snapshot: Snapshot): Candidate[] {
  const parents: number[] = []; const ends: number[] = []; const stack: number[] = [];
  snapshot.nodes.forEach((node, i) => {
    while (stack.length && snapshot.nodes[stack[stack.length - 1]!]!.depth >= node.depth) ends[stack.pop()!] = i;
    parents[i] = stack[stack.length - 1] ?? -1; stack.push(i);
  });
  for (const i of stack) ends[i] = snapshot.nodes.length;
  let dateSection = '';
  const sections: { scope: number; text: string; at: number }[] = [];
  const labels = new Map<string, string>();
  const result = snapshot.nodes.flatMap((node, index) => {
    const heading = (node.role === 'AXHeading' ? node.name || node.value : node.value || node.name).trim();
    if (node.role === 'AXHeading' && heading) sections.push({ scope: parents[index] ?? -1, text: heading, at: index });
    let ancestor = parents[index] ?? -1;
    let insideControl = false;
    while (ancestor >= 0) { if (snapshot.nodes[ancestor]!.actions.includes('AXPress') && node.depth - snapshot.nodes[ancestor]!.depth <= 3) insideControl = true; ancestor = parents[ancestor] ?? -1; }
    if (!insideControl && node.role === 'AXStaticText' && /^(?:Today|Yesterday|(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\b.*)$/i.test(heading)) dateSection = heading;
    const section = [...sections.filter(s => s.scope >= 0 && s.at < index && ends[s.scope]! > index).map(s => s.text), dateSection].filter(Boolean).join(' · ');
    if (!node.enabled || node.value === '[secure]' || !node.actions.includes('AXPress')) return [];
    // Multiline editors are not activation targets. Single-line custom selectors
    // may advertise AXPress to open their options without writing a value.
    if (node.role === 'AXTextArea') return [];
    let editorAncestor = parents[index] ?? -1;
    while (editorAncestor >= 0) {
      if (snapshot.nodes[editorAncestor]!.role === 'AXTextArea' && node.role !== 'AXLink') return [];
      editorAncestor = parents[editorAncestor] ?? -1;
    }
    if (node.role === 'AXGroup') {
      const descendants = snapshot.nodes.slice(index + 1, ends[index]);
      if (descendants.some(child => ['AXTextArea', 'AXTextField', 'AXComboBox', 'AXWebArea'].includes(child.role))) return [];
    }
    const descendants: string[] = [];
    for (let i = index + 1; i < snapshot.nodes.length && snapshot.nodes[i]!.depth > node.depth; i++) {
      const child = snapshot.nodes[i]!;
      if (child.value === '[secure]' || !['AXStaticText', 'AXHeading'].includes(child.role)) continue;
      const label = (child.name || child.value).trim();
      if (label && !descendants.includes(label)) descendants.push(label);
      if (descendants.length >= 8) break;
    }
    const label = node.name.trim() || (['AXTextField','AXComboBox','AXSearchField'].includes(node.role) ? precedingLabel(snapshot, index) : '') || descendants.join(' · ') || 'unlabelled control';
    if (node.role === 'AXGroup' && label === 'unlabelled control') return [];
    labels.set(node.ref, label);
    return [{ id: `a${index}`, description: `${node.role}: ${label.slice(0, 600)}; ref=${node.ref}; current value=${node.value.slice(0, 100)}${section ? `; preceding date section=${section}` : ''}`, action: { kind: 'press' as const, ref: node.ref } }];
  });
  // Chromium often exposes both a clickable wrapper and an identical nested card.
  // Keep the innermost equivalent card; unrelated same-named siblings stay distinct.
  return result.filter(candidate => {
    const index = snapshot.nodes.findIndex(node => node.ref === candidate.action.ref);
    const node = snapshot.nodes[index]!;
    if (!['AXGroup', 'AXPopUpButton', 'AXButton'].includes(node.role)) return true;
    for (let i = index + 1; i < snapshot.nodes.length && snapshot.nodes[i]!.depth > node.depth; i++) {
      const child = snapshot.nodes[i]!;
      if (['AXGroup', 'AXPopUpButton', 'AXButton'].includes(child.role) && child.enabled && child.actions.includes('AXPress') && Boolean(labels.get(child.ref)) && labels.get(node.ref) === labels.get(child.ref)) return false;
    }
    return true;
  });
}

export function textCandidates(snapshot: Snapshot): Candidate[] {
  return snapshot.nodes.flatMap((node, index) => {
    if (!node.enabled || node.value === '[secure]' || !['AXTextField', 'AXTextArea', 'AXComboBox', 'AXSearchField'].includes(node.role)) return [];
    const kind = node.actions.includes('setValue') ? 'setValue' : node.actions.includes('insertText') ? 'insertText' : undefined;
    if (!kind) return [];
    return [{ id: `t${index}`, description: `${node.role}: ${node.name || precedingLabel(snapshot, index) || 'unnamed text field'}; ref=${node.ref}; current value=${node.value.slice(0, 200)}`, action: { kind, ref: node.ref } }];
  });
}

/** Values copied from the user's input, never generated by the decision model. */
export function suppliedTextOptions(goal: string, exact?: string): string[] {
  const values = new Set<string>();
  if (exact?.trim()) values.add(exact);
  for (const match of goal.matchAll(/["“]([^"”]+)["”]/g)) values.add(match[1]!);
  // Long workflows still need exact URLs, domains and reverse-domain IDs.
  // Copy source spans only: never invent a destination from a product name.
  for (const match of goal.matchAll(/https?:\/\/[^\s<>"“”]+/g)) {
    const url = match[0].replace(/[.,;!?\)\]]+$/, '');
    values.add(url);
  }
  for (const match of goal.matchAll(/\b[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)+\b/g)) values.add(match[0]);
  for (const match of goal.matchAll(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)) values.add(match[0]);
  const words = [...goal.matchAll(/[\p{L}\p{N}@._+-]+/gu)].map(m => ({ text: m[0], start: m.index!, end: m.index! + m[0].length }));
  // Bounded phrase enumeration; longer instructions should use the exact-text field.
  if (words.length <= 40) for (let i = 0; i < words.length; i++) for (let length = 1; length <= 3 && i + length <= words.length; length++) {
    values.add(goal.slice(words[i]!.start, words[i + length - 1]!.end));
  }
  return [...values].filter(value => value.length <= 8000).slice(0, 254);
}

/** Walk enclosing groups for sibling labels; do not cross another input field. */
function precedingLabel(snapshot: Snapshot, index: number): string {
  const labels: string[] = [];
  let branch = index;
  while (branch > 0) {
    const depth = snapshot.nodes[branch]!.depth;
    let parent = branch - 1;
    while (parent >= 0 && snapshot.nodes[parent]!.depth >= depth) parent--;
    const siblings = [];
    for (let i = parent + 1; i < branch; i++) {
      const node = snapshot.nodes[i]!;
      if (node.depth === depth) siblings.push(node);
    }
    const heading = [...siblings].reverse().find(n => n.role === 'AXHeading');
    let lastInput = -1;
    siblings.forEach((n, i) => { if (['AXTextField','AXTextArea','AXComboBox'].includes(n.role)) lastInput = i; });
    const label = heading && siblings.indexOf(heading) > lastInput ? heading.name || heading.value
      : siblings.slice(lastInput + 1).find(n => n.role === 'AXStaticText' && n.value !== '[secure]' && (n.name || n.value).trim().length > 1 && (n.name || n.value).length < 120 && !/^\d+$/.test(n.name || n.value));
    const text = typeof label === 'string' ? label : label ? label.name || label.value : '';
    if (text && !labels.includes(text)) labels.unshift(text);
    if (parent < 0 || ['AXWindow','AXWebArea','AXToolbar'].includes(snapshot.nodes[parent]!.role)) break;
    branch = parent;
  }
  return labels.join(' · ');
}

/** Keyboard navigation remains bound to the freshly observed focus receiver. */
export function navigationCandidates(snapshot: Snapshot): Candidate[] {
  const candidates: Candidate[] = [];
  snapshot.nodes.forEach((node, index) => {
    if (!node.enabled || node.value === '[secure]') return;
    let focusedDescendant = false;
    for (let i = index + 1; i < snapshot.nodes.length && snapshot.nodes[i]!.depth > node.depth; i++) {
      if (snapshot.nodes[i]!.focused) { focusedDescendant = true; break; }
    }
    if (!node.focused && node.actions.includes('focus') && !node.actions.includes('AXPress') && ['AXButton','AXMenuButton','AXPopUpButton'].includes(node.role) && node.name.trim()) {
      candidates.push({ id: `f${index}`, description: `Focus ${node.role}: ${node.name} for keyboard activation; this control has no direct press action.`, action: { kind: 'focus', ref: node.ref } });
    }
    if (!node.focused && node.actions.includes('focus') && ['AXTextField','AXTextArea','AXComboBox','AXSearchField'].includes(node.role)) {
      candidates.push({ id: `f${index}`, description: `Focus ${node.role}: ${node.name || precedingLabel(snapshot, index) || 'unnamed field'} without changing its value; use ArrowDown after focus to inspect a selector.`, action: { kind: 'focus', ref: node.ref } });
    }
    if (node.focused && !focusedDescendant && node.actions.length && node.role !== 'AXWindow') {
      const keys: Record<string, string> = {
        'Option+Tab': 'Safari: move forward including custom clickable controls that regular Tab skips',
        'Option+Shift+Tab': 'Safari: move backward including custom clickable controls that regular Shift+Tab skips',
        Tab: 'Move focus forward to the next form control',
        'Shift+Tab': 'Move focus backward to the previous form control',
        ArrowDown: 'Open the focused dropdown, or move to its next option',
        ArrowUp: 'Move to the previous option in the focused dropdown',
        Enter: 'Accept the highlighted dropdown option, or submit the focused form',
        Escape: 'Dismiss the open dropdown or dialog without accepting',
      };
      if (['AXButton','AXMenuButton','AXPopUpButton'].includes(node.role)) keys.Space = 'Activate the focused button using Space';
      for (const [key, purpose] of Object.entries(keys)) candidates.push({
        id: `k${index}_${key.replaceAll('+','')}`, description: `${purpose} (key ${key}); receiver is focused ${node.role}: ${node.name || precedingLabel(snapshot, index) || node.value || 'unnamed control'}`,
        action: { kind: 'backgroundKey', ref: node.ref, text: key },
      });
    }
    if (!snapshot.nodes.some(n => n.focused && ['AXTextField','AXTextArea','AXComboBox','AXGroup'].includes(n.role)) && !node.focused && node.actions.includes('focus') && node.role === 'AXGroup') {
      const labels: string[] = [];
      for (let i = index+1; i < snapshot.nodes.length && snapshot.nodes[i]!.depth > node.depth; i++) {
        const child = snapshot.nodes[i]!;
        if (child.role === 'AXHeading' && child.depth === node.depth + 1 && child.name) labels.push(child.name);
      }
      if (labels.length) candidates.push({ id: `f${index}`, description: `Focus dialog/container ${node.name || labels.join(' · ')} to start keyboard navigation when a custom selector has no press action.`, action: { kind: 'focus', ref: node.ref } });
    }
  });
  return candidates;
}
