export function desktopHTML(base: string) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="referrer" content="no-referrer"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Opcode desktop</title><style>
*{box-sizing:border-box}body{margin:0;background:#101113;color:#eee;font:13px system-ui}header{display:flex;gap:10px;padding:12px 16px;align-items:center;flex-wrap:wrap;background:#191b1e}button,input{font:inherit;color:inherit;border:0;border-radius:5px;background:#2b2e33;height:28px;padding:0 9px}button{cursor:pointer}button:disabled{opacity:.4;cursor:default}button:focus-visible,input:focus-visible{outline:2px solid #90b8ff}#name{width:130px}#status{flex:1;min-width:180px;color:#c0c4cc}#take{background:#d5e3ff;color:#152343}#people{display:flex;gap:10px;padding:8px 16px;min-height:34px;flex-wrap:wrap;color:#b9bec8}.person{display:inline-flex;align-items:center;gap:6px}.dot{width:8px;height:8px;border-radius:100%}#stage{height:calc(100dvh - 108px);display:flex;align-items:center;justify-content:center;padding:8px}#desktop{position:relative;line-height:0;max-width:100%;max-height:100%}#screen{display:block;max-width:100%;max-height:calc(100dvh - 124px);width:auto;height:auto;outline:0;touch-action:none}#cursors{position:absolute;inset:0;pointer-events:none;overflow:hidden}.cursor{position:absolute;top:0;left:0;transition:transform .12s linear;line-height:1;white-space:nowrap}.cursor i{display:block;width:12px;height:17px;clip-path:polygon(0 0,100% 65%,48% 68%,25% 100%);background:currentColor;filter:drop-shadow(0 1px 1px #000)}.cursor span{display:block;font-size:11px;border-radius:4px;padding:4px 6px;margin-left:10px;background:#202329;color:#fff}#hint{position:fixed;bottom:6px;left:0;right:0;text-align:center;color:#8d939f;font-size:11px;pointer-events:none}#stage:fullscreen{background:#101113;height:100vh}#stage:fullscreen #screen{max-height:100vh}
</style></head><body><header><b>Opcode</b><span id="status" role="status">Connecting…</span><input id="name" aria-label="Your display name" placeholder="Your name" maxlength="64"><button id="take" disabled>Take control</button><button id="release" disabled>Release control</button><button id="resize" disabled>Resize</button><button id="full">Fullscreen</button></header><div id="people" aria-label="Participants"></div><main id="stage"><div id="desktop"><img id="screen" tabindex="0" draggable="false" alt="Shared desktop"><div id="cursors" aria-hidden="true"></div></div></main><div id="hint">Everyone has a cursor · One participant controls desktop input · Escape releases control</div><script>
const base=${JSON.stringify(base).replace(/</g, "\\u003c")},key='opcode:'+location.pathname;let token=location.hash.slice(1)||sessionStorage.getItem(key);history.replaceState(null,'',location.pathname+location.search);const frameURL=base+'/frame'+location.search;if(token)sessionStorage.setItem(key,token);
let generation,lease,observation,participant,canControl=false,canPresence=false,busy=false,pointerDown,connected=false,closed=false,denied=false,presenceBusy=false,cursor=null,cursorDirty=false,lastPresence=0,epoch=0;const queue=[];const screen=document.getElementById('screen'),status=document.getElementById('status'),name=document.getElementById('name'),people=document.getElementById('people'),cursors=document.getElementById('cursors');name.value=sessionStorage.getItem(key+':name')||'Guest';const cursorNodes=new Map();
async function api(method,args={},keepalive=false){const response=await fetch(base+'/rpc',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({id:crypto.randomUUID(),method,generation,args}),keepalive,signal:keepalive?undefined:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok||!data.ok){const error=Error(data.error?.message||'Disconnected');error.code=data.error?.code;throw error;}return data.result;}
function controls(){document.getElementById('take').disabled=!connected||!canControl||!!lease||(canPresence&&!participant);document.getElementById('release').disabled=!lease;document.getElementById('resize').disabled=!lease;}
function reset(message){epoch++;connected=false;generation=undefined;lease=undefined;participant=undefined;observation=undefined;pointerDown=undefined;queue.length=0;cursor=null;cursorDirty=false;screen.removeAttribute('src');people.replaceChildren();cursors.replaceChildren();cursorNodes.clear();status.textContent=message;controls();}
async function connect(){const r=await fetch(base+'/session',{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Access expired or revoked');const data=await r.json();if(data.admin){sessionStorage.removeItem(key);token=undefined;denied=true;throw Error('Use a scoped share credential to open the viewer; host credentials are not allowed.');}generation=data.generation;canControl=data.scopes.includes('input-control');canPresence=data.scopes.includes('presence');for(const id of ['take','release','resize'])document.getElementById(id).hidden=!canControl;name.hidden=!canPresence;if(canPresence)participant=await api('presence.join',{name:name.value.trim()||'Guest',role:'human'});connected=true;lastPresence=Date.now();controls();}
function renderPresence(data){const participants=data.participants||[],controller=data.controller;const owned=!!lease&&controller&&controller.participantId===participant?.id;if(lease&&(!controller||(participant&&!owned))){lease=undefined;pointerDown=undefined;queue.length=0;}const owner=participants.find(p=>p.id===controller?.participantId);status.textContent=lease?'You have control':controller?(owner?.name||controller.subject||controller.owner)+' has control':'Watching desktop';if(data.recording?.length)status.textContent+=' · '+data.recording[0].state;const rows=[];const visible=new Set();for(const p of participants){const row=document.createElement('span');row.className='person';const dot=document.createElement('span');dot.className='dot';dot.style.backgroundColor=p.color;const label=document.createElement('span');label.textContent=p.name+(p.id===participant?.id?' (you)':'')+(p.id===controller?.participantId?' · controlling':'');row.append(dot,label);rows.push(row);if(p.id===participant?.id||!p.cursor)continue;const cursorTarget=p.cursor.target||{kind:'display'},frameTarget=observation?.target||{kind:'display'};if(cursorTarget.kind!==frameTarget.kind||(cursorTarget.kind==='window'&&cursorTarget.id!==frameTarget.id))continue;visible.add(p.id);let node=cursorNodes.get(p.id);if(!node){node=document.createElement('div');node.className='cursor';node.append(document.createElement('i'),document.createElement('span'));cursors.append(node);cursorNodes.set(p.id,node);}node.style.color=p.color;node.lastChild.textContent=p.name;node.style.left=(p.cursor.x*100)+'%';node.style.top=(p.cursor.y*100)+'%';}people.replaceChildren(...rows);for(const [id,node] of cursorNodes)if(!visible.has(id)){node.remove();cursorNodes.delete(id);}controls();}
async function frame(){if(closed)return;if(document.hidden||busy){setTimeout(frame,250);return;}const current=epoch;try{if(!connected)await connect();const r=await fetch(frameURL,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Stream unavailable or access expired');const data=await r.json();if(current!==epoch||closed)return;observation=data;screen.src='data:image/png;base64,'+data.image.base64;renderPresence(data);}catch(e){if(!closed)reset(e.message);}finally{if(!closed&&!denied)setTimeout(frame,connected?200:1500);}}
async function heartbeat(){if(closed||!connected||!participant||presenceBusy||document.hidden)return;if(!cursorDirty&&Date.now()-lastPresence<4000)return;presenceBusy=true;const id=participant.id,current=epoch;const next=cursor;cursorDirty=false;try{await api('presence.update',{participantId:id,cursor:next});if(current===epoch)lastPresence=Date.now();}catch(e){if(current===epoch)reset(e.message);}finally{presenceBusy=false;}}
name.onchange=async()=>{name.value=name.value.trim()||'Guest';sessionStorage.setItem(key+':name',name.value);await leave();reset('Updating your name…');};
document.getElementById('take').onclick=async()=>{try{const current=epoch;const acquired=await api('takeover',participant?{participantId:participant.id}:{});if(current!==epoch||closed)return;epoch++;lease=acquired;observation=undefined;controls();status.textContent='You have control';screen.focus();}catch(e){status.textContent=e.message;}};
async function release(keepalive=false){queue.length=0;pointerDown=undefined;if(lease){const old=lease;lease=undefined;controls();await api('release',{leaseId:old.id},keepalive).catch(()=>{});}}
async function leave(keepalive=false){const old=participant;participant=undefined;await Promise.all([release(keepalive),old?api('presence.leave',{participantId:old.id},keepalive).catch(()=>{}):Promise.resolve()]);}
document.getElementById('release').onclick=()=>release();
document.getElementById('resize').onclick=async()=>{if(!lease)return;const size=prompt('Desktop size, e.g. 1280x900');if(!size||!/^\\d+x\\d+$/.test(size))return;const [width,height]=size.split('x').map(Number);try{await api('resize',{leaseId:lease.id,width,height});lease=undefined;observation=undefined;controls();}catch(e){status.textContent=e.message;}};
document.getElementById('full').onclick=()=>{const result=document.fullscreenElement?document.exitFullscreen():document.getElementById('stage').requestFullscreen();result.catch(e=>{status.textContent=e.message;});};
function normalized(e){const r=screen.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};}
function point(e){const p=normalized(e);return {x:p.x*Math.max(0,observation.image.width-1),y:p.y*Math.max(0,observation.image.height-1)};}
function input(action,binding=observation){if(!lease)return;if(queue.length>=16){status.textContent='Input queue full';return;}queue.push({action,leaseId:lease.id,binding});void pump();}
async function pump(){if(busy)return;busy=true;try{while(queue.length&&lease){const next=queue.shift();if(next.leaseId!==lease.id)continue;let observed=next.binding;if(!('x' in next.action)){const r=await fetch(frameURL,{headers:{Authorization:'Bearer '+token},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Access expired or revoked');observed=await r.json();}if(!observed)throw Error('Wait for a fresh frame');if(!lease||next.leaseId!==lease.id)continue;await api('input',{leaseId:next.leaseId,observationId:observed.observationId,action:next.action});}}catch(e){queue.length=0;status.textContent=e.message;if(['lease_conflict','generation_mismatch','permission_denied'].includes(e.code)){lease=undefined;controls();}}finally{busy=false;}}
screen.onpointermove=e=>{if(observation){cursor={...normalized(e),target:observation.target||{kind:'display'}};cursorDirty=true;}};screen.onpointerleave=()=>{cursor=null;cursorDirty=true;};screen.onpointercancel=()=>{pointerDown=undefined;};
screen.onpointerdown=e=>{if(lease&&observation){e.preventDefault();screen.focus();pointerDown={...point(e),button:e.button,binding:observation};screen.setPointerCapture(e.pointerId);}};
screen.onpointerup=e=>{if(!pointerDown||!observation)return;const start=pointerDown;pointerDown=undefined;const end=point(e);input(Math.hypot(end.x-start.x,end.y-start.y)>5?{kind:'drag',x:start.x,y:start.y,toX:end.x,toY:end.y}:{kind:start.button===2?'rightClick':'click',...end},start.binding);};
screen.oncontextmenu=e=>e.preventDefault();screen.onwheel=e=>{if(lease){e.preventDefault();input({kind:'scroll',axis:Math.abs(e.deltaX)>Math.abs(e.deltaY)?'x':'y',amount:Math.sign(Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY)*3});}};
screen.onkeydown=e=>{if(e.key==='Escape'){release();screen.blur();return;}if(!lease)return;e.preventDefault();const mods=[e.ctrlKey?'Control':null,e.altKey?'Alt':null,e.metaKey?'Meta':null,e.shiftKey?'Shift':null].filter(Boolean);if(/^[a-z0-9]$/.test(e.key)&&!mods.length)input({kind:'key',key:e.key});else if(e.key.length===1&&!e.ctrlKey&&!e.altKey&&!e.metaKey)input({kind:'text',text:e.key});else if(!['Control','Shift','Alt','Meta'].includes(e.key))input({kind:'key',key:[...mods,e.key].join('+')});};
screen.onpaste=e=>{if(lease){e.preventDefault();const text=e.clipboardData.getData('text/plain');if(text)input({kind:'text',text});}};
window.onblur=()=>{cursor=null;cursorDirty=true;void release();};document.onvisibilitychange=()=>{if(document.hidden){void leave(true);reset('Desktop paused while this tab is hidden');}};window.addEventListener('pagehide',()=>{closed=true;epoch++;void leave(true);});window.addEventListener('pageshow',e=>{if(e.persisted){closed=false;reset('Reconnecting…');frame();}});
setInterval(heartbeat,100);let renewing=false;setInterval(async()=>{if(!lease||renewing)return;renewing=true;const id=lease.id;try{await api('renew',{leaseId:id});}catch{if(lease?.id===id){lease=undefined;queue.length=0;controls();}}finally{renewing=false;}},10000);frame();
</script></body></html>`;
}
