export function desktopHTML(base: string) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="referrer" content="no-referrer"><title>Opcode desktop</title><style>body{margin:0;background:#101113;color:#eee;font:14px system-ui}header{display:flex;gap:12px;padding:12px;align-items:center}button,input{font:inherit}#screen{display:block;max-width:100%;max-height:calc(100vh - 60px);margin:auto;object-fit:contain;outline:0}#status{flex:1}</style></head><body><header><b>Opcode</b><span id="status">Connecting…</span><button id="take">Take control</button><button id="release">Return control</button><button id="resize">Resize</button><button id="full">Fullscreen</button></header><img id="screen" tabindex="0" draggable="false" alt="Desktop stream"><script>
const base=${JSON.stringify(base)},key='opcode:'+location.pathname;let token=location.hash.slice(1)||sessionStorage.getItem(key);history.replaceState(null,'',location.pathname+location.search);const frameURL=base+'/frame'+location.search;if(token)sessionStorage.setItem(key,token);
let generation,lease,observation,active=true,busy=false,pointerDown;const queue=[];const screen=document.getElementById('screen'),status=document.getElementById('status');
async function api(method,args={}){const response=await fetch(base+'/rpc',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({id:crypto.randomUUID(),method,generation,args})});const data=await response.json();if(!response.ok||!data.ok)throw Error(data.error?.message||'Disconnected');return data.result;}
async function connect(){const r=await fetch(base+'/session',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Access expired or revoked');const data=await r.json();generation=data.generation;for(const id of ['take','release','resize'])document.getElementById(id).hidden=!data.scopes.includes('input-control');}
async function frame(){if(!active||document.hidden||busy){setTimeout(frame,250);return;}try{if(!generation)await connect();const r=await fetch(frameURL,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Stream unavailable or access expired');const data=await r.json();observation=data;screen.src='data:image/png;base64,'+data.image.base64;status.textContent=(lease?'You have control':'Watching desktop')+(data.recording?.length?' · '+data.recording[0].state:'');}catch(e){status.textContent=e.message;generation=undefined;lease=undefined;screen.removeAttribute('src');queue.length=0;}setTimeout(frame,200);}
document.getElementById('take').onclick=async()=>{try{lease=await api('takeover');observation=undefined;screen.focus();}catch(e){status.textContent=e.message;}};
async function release(){queue.length=0;if(lease){const old=lease;lease=undefined;await api('release',{leaseId:old.id}).catch(()=>{});}}
document.getElementById('release').onclick=release;
document.getElementById('resize').onclick=async()=>{if(!lease)return;const size=prompt('Desktop size, e.g. 1280x900');if(!size||!/^\\d+x\\d+$/.test(size))return;const [width,height]=size.split('x').map(Number);try{await api('resize',{leaseId:lease.id,width,height});lease=undefined;observation=undefined;}catch(e){status.textContent=e.message;}};
document.getElementById('full').onclick=()=>document.fullscreenElement?document.exitFullscreen():screen.requestFullscreen();
function point(e){const r=screen.getBoundingClientRect();return {x:(e.clientX-r.left)*observation.image.width/r.width,y:(e.clientY-r.top)*observation.image.height/r.height};}
function input(action,binding=observation){if(!lease)return;if(queue.length>=16){status.textContent='Input queue full';return;}queue.push({action,leaseId:lease.id,binding});void pump();}
async function pump(){if(busy)return;busy=true;try{while(queue.length&&lease){const next=queue.shift();if(next.leaseId!==lease.id)continue;let observed=next.binding;if(!('x' in next.action)){const r=await fetch(frameURL,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Access expired or revoked');observed=await r.json();}if(!observed)throw Error('Wait for a fresh frame');await api('input',{leaseId:next.leaseId,observationId:observed.observationId,action:next.action});}}catch(e){queue.length=0;status.textContent=e.message;}finally{busy=false;}}

screen.onpointerdown=e=>{if(lease&&observation){e.preventDefault();pointerDown={...point(e),button:e.button,binding:observation};screen.setPointerCapture(e.pointerId);}};
screen.onpointerup=e=>{if(!pointerDown||!observation)return;const start=pointerDown;pointerDown=undefined;const end=point(e);input(Math.hypot(end.x-start.x,end.y-start.y)>5?{kind:'drag',x:start.x,y:start.y,toX:end.x,toY:end.y}:{kind:start.button===2?'rightClick':'click',...end},start.binding);};
screen.oncontextmenu=e=>e.preventDefault();screen.onwheel=e=>{if(lease){e.preventDefault();input({kind:'scroll',axis:Math.abs(e.deltaX)>Math.abs(e.deltaY)?'x':'y',amount:Math.sign(Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY)*3});}};
screen.onkeydown=e=>{if(e.key==='Escape'){release();screen.blur();return;}if(!lease)return;e.preventDefault();const mods=[e.ctrlKey?'Control':null,e.altKey?'Alt':null,e.metaKey?'Meta':null,e.shiftKey?'Shift':null].filter(Boolean);if(/^[a-z0-9]$/.test(e.key)&&!mods.length)input({kind:'key',key:e.key});else if(e.key.length===1&&!mods.length)input({kind:'text',text:e.key});else if(!['Control','Shift','Alt','Meta'].includes(e.key))input({kind:'key',key:[...mods,e.key].join('+')});};
screen.onpaste=e=>{if(lease){e.preventDefault();const text=e.clipboardData.getData('text/plain');if(text)input({kind:'text',text});}};
window.onblur=()=>{pointerDown=undefined;release();};document.onvisibilitychange=()=>{if(document.hidden)release();};
setInterval(()=>{if(lease)api('renew',{leaseId:lease.id}).catch(()=>{lease=undefined;});},10000);frame();
</script></body></html>`;
}
